### ISSUE TITLE
番茄小说爬虫出错

### ISSUE THREAD

**Issue by youyouzz** [UnAbuse/Elegant_finder#8]
direct返回的是目录的list，但是只有item_id，没有其他的title之类的信息。
content返回报错，提示cookie有问题。
不知道能不能出一个示范代码，讲解得更详细一点

**Comment by youyouzz** [comment]
content_url 页面出问题了，作者能不能看看什么情况？{"code":1101001,"data":null,"log_id":"202305201505415817577D86E28F4F62DA","message":"请重启app或升级至最新版本"}

**Comment by jinjf553** [comment]
> content_url 页面出问题了，作者能不能看看什么情况？{"code":1101001,"data":null,"log_id":"202305201505415817577D86E28F4F62DA","message":"请重启app或升级至最新版本"}

self.content_url = 'https://novel.snssdk.com/api/novel/book/reader/full/v1/'   这个链接有问题，我尝试把full换成content后，请求是成功的，但是data数据为空。
