### ISSUE TITLE
正文链接获取失败

### ISSUE THREAD

**Issue by kongxiyi** [UnAbuse/Elegant_finder#9]
正文内容获取失败，报错如下，
url = https://novel.snssdk.com/api/novel/book/reader/full/v1/
```
data: {
    code: 1101001,
    data: null,
    log_id: '2023090411573051A1A26C5FC02A5BBA0D',
    message: '请重启app或升级至最新版本'
  }
```

**Comment by KamiyaLIUC** [comment]
py小白，搜索了很多方法，这里粗浅提供一下我的解决思路
提供一个新的context地址，https://novel.snssdk.com/api/novel/book/reader/full/v1/?device_platform=android&parent_enterfrom=novel_channel_search.tab.&aid=2329&platform_id={item_id}&item_id={item_id}，
header文件中不需要cookies可以直接删除，新的地址需要itemid也就是章节id，我将它放在了def content(self, item_id):中
将content_info = self.meth.get_Html中的params配置删除，运行后成功
